package sunaba.ui;

import sunaba.core.Dictionary;
import sunaba.core.Event;
import sunaba.core.Color;
import sunaba.core.Resource;
import sunaba.core.Variant;
import sunaba.core.Vector2;

@:native("CodeEdit")
extern class CodeEdit extends TextEdit {
    public var autoBraceCompletionEnabled: Bool;
    public var autoBraceCompletionHighlightMatching: Bool;
    public var autoBraceCompletionPairs: Dictionary;
    public var codeCompletionEnabled: Bool;
    public var codeCompletionPrefixes: Array<String>;
    public var delimiterComments: Array<String>;
    public var delimiterStrings: Array<String>;
    public var guttersDrawBookmarks: Bool;
    public var guttersDrawBreakpointsGutter: Bool;
    public var guttersDrawExecutingLines: Bool;
    public var guttersDrawFoldGutter: Bool;
    public var guttersDrawLineNumbers: Bool;
    public var guttersZeroPadLineNumbers: Bool;
    public var indentAutomatic: Bool;
    public var indentAutomaticPrefixes: Array<String>;
    public var indentSize: Int;
    public var indentUseSpaces: Bool;
    public var layoutDirection: Float;
    public var lineFolding: Bool;
    public var lineLengthGuidelines: Array<Int>;
    public var symbolLookupOnClick: Bool;
    public var symbolTooltipOnHover: Bool;
    public var textDirection: Int;
    public var breakpointToggled: Event;
    public var codeCompletionRequested: Event;
    public var symbolHovered: Event;
    public var symbolLookup: Event;
    public var symbolValidate: Event;
    public function addAutoBraceCompletionPair(startKey: String, endKey: String): Void;
    public function addCodeCompletionOption(type: Int, displayText: String, insertText: String, textColor: Color, ?icon: Resource, ?value: Variant, ?location: Int): Void;
    public function addCommentDelimiter(startKey: String, endKey: String, ?lineOnly: Bool): Void;
    public function addStringDelimiter(startKey: String, endKey: String, ?lineOnly: Bool): Void;
    public function canFoldLine(line: Int): Bool;
    public function cancelCodeCompletion(): Void;
    public function clearBookmarkedLines(): Void;
    public function clearBreakpointedLines(): Void;
    public function clearCommentDelimiters(): Void;
    public function clearExecutingLines(): Void;
    public function clearStringDelimiters(): Void;
    public function confirmCodeCompletion(): Void;
    public function convertIndent(?fromLine: Int, ?toLine: Int): Void;
    public function createCodeRegion(): Void;
    public function deleteLines(): Void;
    public function doIndent(): Void;
    public function duplicateLines(): Void;
    public function duplicateSelection(): Void;
    public function foldAllLines(): Void;
    public function foldLine(line: Int): Void;
    public function getAutoBraceCompletionCloseKey(opneKey: String): String;
    public function getBookmarkedLines(): Array<Int>;
    public function getBreakpointedLines(): Array<Int>;
    public function getCodeCompletionOption(index: Int): Dictionary;
    public function getCodeCompletionOptions(): Array<Dictionary>;
    public function getCodeCompletionSelectedIndex(): Int;
    public function getCodeRegionEndTag(): String;
    public function getCodeRegionStartTag(): String;
    public function getDelimiterEndKey(delimiterIndex: Int): String;
    public function getDelimiterEndPosition(line: Int, column: Int): Vector2;
    public function getDelimiterStartKey(delimiterIndex: Int): String;
    public function getDelimiterStartPosition(line: Int, column: Int): Vector2;
    public function getExecutingLines(): Array<Int>;
}