package sunaba.ui;

import sunaba.core.ArrayList;
import sunaba.core.Variant;
import sunaba.core.Rect2;
import sunaba.core.Color;
import sunaba.core.Vector2i;
import sunaba.desktop.PopupMenu;
import sunaba.core.Dictionary;
import sunaba.core.Font;

@:native("PanelContainer")
extern class RichTextLabel extends Control {
    public var autowrapMode: Int;
    public var bbcodeEnabled: Bool;
    public var clipContents: Bool;
    public var contextMenuEnabled: Bool;
    public var customEffects: ArrayList;
    public var deselectOnFocusLossEnabled: Bool;
    public var dragAndDropSelectionEnabled: Bool;
    public var fitContent: Bool;
    public var hintUnderlined: Bool;
    public var horizontalAlignment: Int;
    public var justificationFlags: Int;
    public var language: String;
    public var metaUnderlined: Bool;
    public var progressBarDelay: Int;
    public var scrollActive: Bool;
    public var scrollFollowing: Bool;
    public var selectionEnabled: Bool;
    public var shortcutKeysEnabled: Bool;
    public var structuredTextBidiOverride: Int;
    public var structuredTextBidiOverrideOptions: ArrayList;
    public var tabSize: Int;
    public var tabStops: Array<Float>;
    public var text: String;
    public var textDirection: Int;
    public var threaded: Bool;
    public var verticalAlignment: Int;
    public var visibleCharacters: Int;
    public var visibleCharactersBehavior: Int;
    public var visibleRatio: Float;
    public var finished: sunaba.core.Event;
    public var metaClicked: sunaba.core.Event;
    public var metaHoverEnded: sunaba.core.Event;
    public var metaHoverStarted: sunaba.core.Event;
    public function addImage(image: sunaba.core.Texture2D, ?width: Int, ?height: Int, ?color: Color, ?inlineAlign: Int, ?region: Rect2, ?key: Variant, ?pad: Bool, ?tooltip: String, ?sizeInPercent: Bool ): Void;
    public function addText(text: String): Void;
    public function appendText(bbcode: String): Void;
    public function clear(): Void;
    public function deselect(): Void;
    public function getCharacterLine(character: Int): Int;
    public function getCharacterParagraph(character: Int): Int;
    public function getContentHeight(): Float;
    public function getContentWidth(): Float;
    public function getLineCount(): Int;
    public function getLineOffset(line: Int): Float;
    public function getLineRange(line: Int): Vector2i;
    public function getMenu(): PopupMenu;
    public function getParagraphCount(): Int;
    public function getParagraphOffset(paragraph: Int): Float;
    public function getParsedText(): String;
    public function getSelectedText(): String;
    public function getSelectionFrom(): Int;
    public function getSelectionLineOffset(): Float;
    public function getSelectionTo(): Int;
    public function getTotalCharacterCount(): Int;
    //public function getVScrollBar(): ScrollBar;
    public function getVisibleLineCount(): Int;
    public function getVisibleParagraphCount(): Int;
    public function installEffect(effect: Variant): Void;
    public function invalidateParagraph(paragraph: Int): Bool;
    public function isFinished(): Bool;
    public function isMenuVisible(): Bool;
    public function isReady(): Bool;
    public function menuOption(option: Int): Void;
    public function newline(): Void;
    public function parseBBCode(bbcode: String): Void;
    public function parseExpressionsForValues(expressions: Array<String>): Dictionary;
    public function pop(): Void;
    public function popAll(): Void;
    public function popContent(): Void;
    public function pushBgcolor(bgcolor: Color): Void;
    public function pushBold(): Void;
    public function pushBoldItalics(): Void;
    public function pushCell(): Void;
    public function pushColor(color: Color): Void;
    public function pushContext(): Void;
    public function pushDropcap(string: String, font: Font, size: Int, ?dropcapMargins: Rect2, ?color: Color, ?outlineSize: Int, ?outlineColor: Color): Void;
    public function pushFgcolor(fgcolor: Color): Void;
    public function pushFont(font: Font): Void;
    public function pushFontSize(size: Int): Void;
    public function pushHint(description: String): Void;
    public function pushIndent(level: Int): Void;
    public function pushItalics(): Void;
    public function pushLanguage(language: String): Void;
    public function pushList(level: Int, type: Int, capitalize: Bool, ?bullet: String): Void;
    public function pushMeta(data: Variant, ?underlineMode: Int, ?tooltip: String): Void;
    public function pushMono(): Void;
    public function pushNormal(): Void;
    public function pushOutlineColor(color: Color): Void;
}