package sunaba.ui;

import sunaba.core.ArrayList;
import sunaba.core.Event;

@:native("TextEdit")
extern class TextEdit extends Control {
    public var autowrapMode: Int;
    public var caretBlink: Bool;
    public var caretBlinkInterval: Float;
    public var caretDrawWhenEditableDisabled: Bool;
    public var caretMidGrapheme: Bool;
    public var caretMoveOnRightClick: Bool;
    public var caretMultiple: Bool;
    public var caretType: Int;
    public var clipContents: Bool;
    public var contextMenuEnabled: Bool;
    public var customWordSeparators: String;
    public var deselectOnFocusLost: Bool;
    public var dragAndDropSelectionEnabled: Bool;
    public var drawControlChars: Bool;
    public var drawSpaces: Bool;
    public var editable: Bool;
    public var emojuMenuEnabled: Bool;
    public var emptySelectionClipboardEnabled: Bool;
    public var highlightAllOccurrences: Bool;
    public var highlightCurrentLine: Bool;
    public var indentWrappedLines: Bool;
    public var language: String;
    public var middleMousePasteEnabled: Bool;
    public var minimapDraw: Bool;
    public var minimapWidth: Int;
    public var mouseDefaultCursorShape: Int;
    public var placeholderText: String;
    public var scrollFitContentHeight: Bool;
    public var scrollFitContentWidth: Bool;
    public var scrollHorizontal: Int;
    public var scrollPastEndOfFile: Bool;
    public var scrollSmooth: Bool;
    public var scrollVScrollSpeed: Float;
    public var scrollVertical: Float;
    public var selectingEnabled: Bool;
    public var shortcutKeysEnabled: Bool;
    public var structuredTextBidiOverride: Bool;
    public var structuredTextBidiOverrideOptions: ArrayList;
    public var syntaxHighlighter: SyntaxHighlighter;
    public var text: String;
    public var textDirection: Int;
    public var useCustomWordSeparators: Bool;
    public var useDefaultWordSeparators: Bool;
    public var virtualKeyboardEnabled: Bool;
    public var wrapMode: Int;
    public var caretChanged: Event;
    public var gutterAdded: Event;
    public var gutterClicked: Event;
    public var gutterRemoved: Event;
    public var linesEditedFrom: Event;
    public var textChanged: Event;
    public var textSet: Event;
    public function addCaret(line: Int, column: Int): Int;
    public function addCaretAtCarets(bellow: Bool): Void;
    public function addGutter(?at: Int): Void;
}