#include "tree_item.h"

namespace sunaba::ui {
    void bindTreeItem(sol::state& lua) {
        lua.new_usertype<TreeItem>("TreeItem",
            sol::constructors<TreeItem()>(),
            sol::base_classes, sol::bases<BaseObject>(),
            "collapsed", sol::property(&TreeItem::getCollapsed, &TreeItem::setCollapsed),
            "customMinimumHeight", sol::property(&TreeItem::getCustomMinimumHeight, &TreeItem::setCustomMinimumHeight),
            "disableFolding", sol::property(&TreeItem::getDisableFolding, &TreeItem::setDisableFolding),
            "visible", sol::property(&TreeItem::getVisible, &TreeItem::setVisible),
            "addButton", &TreeItem::addButton,
            "addChild", &TreeItem::addChild,
            "clearButtons", &TreeItem::clearButtons,
            "clearCustomBgColor", &TreeItem::clearCustomBgColor,
            "clearCustomColor", &TreeItem::clearCustomColor,
            "createChild", &TreeItem::createChild,
            "deselect", &TreeItem::deselect,
            "eraseButton", &TreeItem::eraseButton,
            "getAutoTranslateMode", &TreeItem::getAutoTranslateMode,
            "getAutowrapMode", &TreeItem::getAutowrapMode,
            "getButton", &TreeItem::getButton,
            "getButtonById", &TreeItem::getButtonById,
            "getButtonColor", &TreeItem::getButtonColor,
            "getButtonCount", &TreeItem::getButtonCount,
            "getButtonId", &TreeItem::getButtonId,
            "getButtonTooltipText", &TreeItem::getButtonTooltipText,
            "getCellMode", &TreeItem::getCellMode,
            "getChild", &TreeItem::getChild,
            "getChildCount", &TreeItem::getChildCount,
            "getChildren", &TreeItem::getChildren,
            "getCustomBgColor", &TreeItem::getCustomBgColor,
            "getCustomColor", &TreeItem::getCustomColor,
            "getCustomFont", &TreeItem::getCustomFont,
            "getCustomFontSize", &TreeItem::getCustomFontSize,
            "getExpandRight", &TreeItem::getExpandRight,
            "getFirstChild", &TreeItem::getFirstChild,
            "getIcon", &TreeItem::getIcon,
            "getIconMaxWidth", &TreeItem::getIconMaxWidth,
            "getIconModulate", &TreeItem::getIconModulate,
            "getIconOverlay", &TreeItem::getIconOverlay,
            "getIconRegion", &TreeItem::getIconRegion,
            "getIndex", &TreeItem::getIndex,
            "getLanguage", &TreeItem::getLanguage,
            "getMetadata", &TreeItem::getMetadata,
            "getNext", &TreeItem::getNext,
            "getNextInTree", &TreeItem::getNextInTree,
            "getNextVisible", &TreeItem::getNextVisible,
            "getParent", &TreeItem::getParent,
            "getPrev", &TreeItem::getPrev,
            "getPrevInTree", &TreeItem::getPrevInTree,
            "getPrevVisible", &TreeItem::getPrevVisible,
            "getRange", &TreeItem::getRange,
            "getRangeConfig", &TreeItem::getRangeConfig,
            "getStructuredTextBidiOverride", &TreeItem::getStructuredTextBidiOverride,
            "getStructuredTextBdidOverrideOptions", &TreeItem::getStructuredTextBidiOverrideOptions,
            "getSuffix", &TreeItem::getSuffix,
            "getText", &TreeItem::getText,
            "getTextAlignment", &TreeItem::getTextAlignment,
            "getTextDirection", &TreeItem::getTextDirection,
            "getTextOverrunBehavior", &TreeItem::getTextOverrunBehavior,
            "getTooltipText", &TreeItem::getTooltipText,
            "getTree", &TreeItem::getTree,
            "isAnyCollapsed", &TreeItem::isAnyCollapsed,
            "isButtonDisabled", &TreeItem::isButtonDisabled,
            "isChecked", &TreeItem::isChecked,
            "isCustomSetAsButton", &TreeItem::isCustomSetAsButton,
            "isEditMultiline", &TreeItem::isEditMultiline,
            "isEditable", &TreeItem::isEditable,
            "isIndeterminate", &TreeItem::isIndeterminate,
            "isSelectable", &TreeItem::isSelectable,
            "isSelected", &TreeItem::isSelected,
            "isVisibleInTree", &TreeItem::isVisibleInTree,
            "moveAfter", &TreeItem::moveAfter,
            "moveBefore", &TreeItem::moveBefore,
            "propagateCheck", &TreeItem::propagateCheck,
            "removeChild", &TreeItem::removeChild,
            "select", &TreeItem::select,
            "setAutoTranslateMode", &TreeItem::setAutoTranslateMode,
            "setAutowrapMode", &TreeItem::setAutowrapMode,
            "setButton", &TreeItem::setButton,
        );
    }
}