package sunaba.desktop;

import sunaba.core.Event;
import sunaba.input.InputEvent;
import sunaba.input.Shortcut;
import sunaba.core.Texture2D;
import sunaba.core.Color;
import sunaba.core.Variant;

@:native("PopupMenu")
extern class PopupMenu extends Popup {
    public var allowSearch: Bool;
    public var hideOnCheckableItemSelection: Bool;
    public var hideOnItemSelection: Bool;
    public var hideOnStateItemSelection: Bool;
    public var itemCount: Int;
    public var preferNativeMenu: Bool;
    public var submenuPopupDelay: Float;
    public var systemMenuId: Int;
    public var idFocused: Event;
    public var idPressed: Event;
    public var menuChanged: Event;
    public function activateItemByEvent(event: InputEvent, ?forGlobalOnly: Bool) : Void;
    public function addCheckItem(label: String, ?id: Int, ?accel: Int): Void;
    public function addCheckShortcut(shortcut: Shortcut, ?id: Int, ?global: Bool): Void;
    public function addIconCheckItem(texture: Texture2D, label: String, ?id: Int, ?accel: Int): Void;
    public function addIconCheckShortcut(texture: Texture2D, shortcut: Shortcut, ?id: Int, ?global: Bool): Void;
    public function addIconItem(texture: Texture2D, label: String, ?id: Int, ?accel: Int): Void;
    public function addIconRadioCheckItem(texture: Texture2D, label: String, ?id: Int, ?accel: Int): Void;
    public function addIconRadioCheckShortcut(texture: Texture2D, shortcut: Shortcut, ?id: Int, ?global: Bool): Void;
    public function addIconShortcut(texture: Texture2D, shortcut: Shortcut, ?id: Int, ?global: Bool, ?allowEcho: Bool): Void;
    public function addItem(label: String, id: Int, ?accel: Int): Void;
    public function addMultistateItem(label: String, maxStates: Int, defaultState: Int, ?id: Int, ?accel: Int): Void;
    public function addRadioCheckItem(label: String, ?id: Int, ?accel: Int): Void;
    public function addRadioCheckShortcut(shortcut: Shortcut, ?id: Int, ?global: Bool): Void;
    public function addSeparator(?label: String, ?id: Int): Void;
    public function addShortcut(shortcut: Shortcut, ?id: Int, ?global: Bool, ?allowEcho: Bool): Void;
    public function addSubmenuItem(label: String, submenu: String, ?id: Int, ?accel: Int): Void;
    public function addSubmenuNodeItem(label: String, submenu: PopupMenu, ?id: Int, ?accel: Int): Void;
    public function clear(?freeSubmenus: Bool): Void;
    public function getFocusedItem(): Int;
    public function getItemAccelerator(index: Int): Int;
    public function getItemIcon(index: Int): Texture2D;
    public function getItemIconMaxWidth(index: Int): Int;
    public function getItemIconModulate(index: Int): Color;
    public function getItemId(index: Int): Int;
    public function getItemIndent(id: Int): Int;
    public function getItemLanguage(index: Int): String;
    public function getItemMetadata(index: Int): Variant;
    public function getItemMultistate(index: Int): Int;
    public function getItemMultistateMax(index: Int): Int;
    public function getItemShortcut(index: Int): Shortcut;
    public function getItemSubmenu(index: Int): String;
    public function getItemSubmenuNode(index: Int): PopupMenu;
    public function getItemText(index: Int): String;
    public function getItemTextDirection(index: Int): Int;
    public function getItemTooltip(index: Int): String;
    public function isItemCheckable(index: Int): Bool;
    public function isItemChecked(index: Int): Bool;
    public function isItemDisabled(index: Int): Bool;
    public function isItemRadioCheckable(index: Int): Bool;
    public function isItemSeparator(index: Int): Bool;
    public function isItemShortcutDisabled(index: Int): Bool;
    public function isSystemMenu(): Bool;
    public function removeItem(id: Int): Void;
    public function scrollToItem(id: Int): Void;
    public function setFocusedItem(id: Int): Void;
    public function setItemAccelerator(id: Int, accel: Int): Void;
    public function setItemAsCheckable(id: Int, checkable: Bool): Void;
    public function setItemAsRadioCheckable(id: Int, radioCheckable: Bool): Void;
    public function setItemAsSeparator(id: Int, separator: Bool): Void;
    public function setItemChecked(id: Int, checked: Bool): Void;
    public function setItemDisabled(id: Int, disabled: Bool): Void;
    public function setItemIcon(id: Int, texture: Texture2D): Void;
}