package sunaba;

enum abstract godot_variant_call_error_error(Int) {
	var GODOT_CALL_ERROR_CALL_OK = 0;
	var GODOT_CALL_ERROR_CALL_ERROR_INVALID_METHOD = 1;
	var GODOT_CALL_ERROR_CALL_ERROR_INVALID_ARGUMENT = 2;
	var GODOT_CALL_ERROR_CALL_ERROR_TOO_MANY_ARGUMENTS = 3;
	var GODOT_CALL_ERROR_CALL_ERROR_TOO_FEW_ARGUMENTS = 4;
	var GODOT_CALL_ERROR_CALL_ERROR_INSTANCE_IS_NULL = 5;
	var GODOT_CALL_ERROR_CALL_ERROR_METHOD_NOT_CONST = 6;
}
