#include "image.h"

void kenai::core::bindImage(sol::state &lua) {
    lua.new_usertype<kenai::core::Image>("Image",
        "new", sol::factories(
            []() { return new kenai::core::Image(); }
        ),
        sol::base_classes, sol::bases<kenai::core::BaseObject, kenai::core::Resource>(),
        "adjustBcs", &kenai::core::Image::adjustBcs,
        "blendRect", &kenai::core::Image::blendRect,
        "blendRectMask", &kenai::core::Image::blendRectMask,
        "blitRect", &kenai::core::Image::blitRect,
        "blitRectMask", &kenai::core::Image::blitRectMask,
        "crop", &kenai::core::Image::crop,
        //"cropRect", &kenai::core::Image::cropRect,
        "flipX", &kenai::core::Image::flipX,
        "flipY", &kenai::core::Image::flipY,
        "generateMipmaps", &kenai::core::Image::generateMipmaps,
        "getData", &kenai::core::Image::getData,
        "getDataSize", &kenai::core::Image::getDataSize,
        "getFormat", &kenai::core::Image::getFormat,
        "getHeight", &kenai::core::Image::getHeight,
        "getMipmapCount", &kenai::core::Image::getMipmapCount,
        "getMipmapOffset", &kenai::core::Image::getMipmapOffset,
        "getPixel", &kenai::core::Image::getPixel,
        "getPixelv", &kenai::core::Image::getPixelv,
        "getRegion", &kenai::core::Image::getRegion,
        "getSize", &kenai::core::Image::getSize,
        "getUsedRect", &kenai::core::Image::getUsedRect,
        "getWidth", &kenai::core::Image::getWidth,
        "hasMipmaps", &kenai::core::Image::hasMipmaps,
        "isCompressed", &kenai::core::Image::isCompressed,
        "isEmpty", &kenai::core::Image::isEmpty,
        "isInvisible", &kenai::core::Image::isInvisible,
        "load", &kenai::core::Image::load,
        "loadBmpFromBuffer", &kenai::core::Image::loadBmpFromBuffer,
        "loadFromFile", &kenai::core::Image::loadFromFile,
        "loadJpegFromBuffer", &kenai::core::Image::loadJpegFromBuffer,
        "loadKtxFromBuffer", &kenai::core::Image::loadKtxFromBuffer,
        "loadPngFromBuffer", &kenai::core::Image::loadPngFromBuffer,
        "loadSvgFromBuffer", &kenai::core::Image::loadSvgFromBuffer,
        "loadSvgFromString", &kenai::core::Image::loadSvgFromString,
        "loadTgaFromBuffer", &kenai::core::Image::loadTgaFromBuffer,
        "loadWebpFromBuffer", &kenai::core::Image::loadWebpFromBuffer,
        "normalMapToXY", &kenai::core::Image::normalMapToXY,
        "premultiplyAlpha", &kenai::core::Image::premultiplyAlpha,
        "resize", &kenai::core::Image::resize,
        "resizeToPo2", &kenai::core::Image::resizeToPo2,
        "rotate90", &kenai::core::Image::rotate90,
        "rotate180", &kenai::core::Image::rotate180,
        "saveRxr", &kenai::core::Image::saveRxr,
        "saveRxrToBuffer", &kenai::core::Image::saveRxrToBuffer,
        "saveJpeg", &kenai::core::Image::saveJpeg,
        "saveJpegToBuffer", &kenai::core::Image::saveJpegToBuffer,
        "savePng", &kenai::core::Image::savePng,
        "savePngToBuffer", &kenai::core::Image::savePngToBuffer,
        "saveWebp", &kenai::core::Image::saveWebp,
        "saveWebpToBuffer", &kenai::core::Image::saveWebpToBuffer,
        //"setData", &kenai::core::Image::setData,
        "setPixel", &kenai::core::Image::setPixel,
        "setPixelv", &kenai::core::Image::setPixelv,
        "shrinkX2", &kenai::core::Image::shrinkX2,
        "srgbToLinear", &kenai::core::Image::srgbToLinear,
        "cast", [](Resource* instance) {
            return new Image(godot::Object::cast_to<GodotImage>(instance->getResource()));
        }
    );
}