#include "image.h"

void sunaba::core::bindImage(sol::state &lua) {
    lua.new_usertype<sunaba::core::Image>("Image",
        "new", sol::factories(
            []() { return new sunaba::core::Image(); }
        ),
        sol::base_classes, sol::bases<sunaba::core::BaseObject, sunaba::core::Resource>(),
        "adjustBcs", &sunaba::core::Image::adjustBcs,
        "blendRect", &sunaba::core::Image::blendRect,
        "blendRectMask", &sunaba::core::Image::blendRectMask,
        "blitRect", &sunaba::core::Image::blitRect,
        "blitRectMask", &sunaba::core::Image::blitRectMask,
        "crop", &sunaba::core::Image::crop,
        //"cropRect", &sunaba::core::Image::cropRect,
        "flipX", &sunaba::core::Image::flipX,
        "flipY", &sunaba::core::Image::flipY,
        "generateMipmaps", &sunaba::core::Image::generateMipmaps,
        "getData", &sunaba::core::Image::getData,
        "getDataSize", &sunaba::core::Image::getDataSize,
        "getFormat", &sunaba::core::Image::getFormat,
        "getHeight", &sunaba::core::Image::getHeight,
        "getMipmapCount", &sunaba::core::Image::getMipmapCount,
        "getMipmapOffset", &sunaba::core::Image::getMipmapOffset,
        "getPixel", &sunaba::core::Image::getPixel,
        "getPixelv", &sunaba::core::Image::getPixelv,
        "getRegion", &sunaba::core::Image::getRegion,
        "getSize", &sunaba::core::Image::getSize,
        "getUsedRect", &sunaba::core::Image::getUsedRect,
        "getWidth", &sunaba::core::Image::getWidth,
        "hasMipmaps", &sunaba::core::Image::hasMipmaps,
        "isCompressed", &sunaba::core::Image::isCompressed,
        "isEmpty", &sunaba::core::Image::isEmpty,
        "isInvisible", &sunaba::core::Image::isInvisible,
        "load", &sunaba::core::Image::load,
        "loadBmpFromBuffer", &sunaba::core::Image::loadBmpFromBuffer,
        "loadFromFile", &sunaba::core::Image::loadFromFile,
        "loadJpegFromBuffer", &sunaba::core::Image::loadJpegFromBuffer,
        "loadKtxFromBuffer", &sunaba::core::Image::loadKtxFromBuffer,
        "loadPngFromBuffer", &sunaba::core::Image::loadPngFromBuffer,
        "loadSvgFromBuffer", &sunaba::core::Image::loadSvgFromBuffer,
        "loadSvgFromString", &sunaba::core::Image::loadSvgFromString,
        "loadTgaFromBuffer", &sunaba::core::Image::loadTgaFromBuffer,
        "loadWebpFromBuffer", &sunaba::core::Image::loadWebpFromBuffer,
        "normalMapToXY", &sunaba::core::Image::normalMapToXY,
        "premultiplyAlpha", &sunaba::core::Image::premultiplyAlpha,
        "resize", &sunaba::core::Image::resize,
        "resizeToPo2", &sunaba::core::Image::resizeToPo2,
        "rotate90", &sunaba::core::Image::rotate90,
        "rotate180", &sunaba::core::Image::rotate180,
        "saveRxr", &sunaba::core::Image::saveRxr,
        "saveRxrToBuffer", &sunaba::core::Image::saveRxrToBuffer,
        "saveJpeg", &sunaba::core::Image::saveJpeg,
        "saveJpegToBuffer", &sunaba::core::Image::saveJpegToBuffer,
        "savePng", &sunaba::core::Image::savePng,
        "savePngToBuffer", &sunaba::core::Image::savePngToBuffer,
        "saveWebp", &sunaba::core::Image::saveWebp,
        "saveWebpToBuffer", &sunaba::core::Image::saveWebpToBuffer,
        //"setData", &sunaba::core::Image::setData,
        "setPixel", &sunaba::core::Image::setPixel,
        "setPixelv", &sunaba::core::Image::setPixelv,
        "shrinkX2", &sunaba::core::Image::shrinkX2,
        "srgbToLinear", &sunaba::core::Image::srgbToLinear,
        "cast", [](Resource* instance) {
            return new Image(godot::Object::cast_to<GodotImage>(instance->getResource()));
        }
    );
}