package sunaba.core;

import sunaba.spatial.World3D;
import sunaba.ui.Control;

@:native("Viewport")
extern class Viewport extends Element {
    public var anisotropicFilteringLevel: Int;
    public var audioListenerEnable2D: Bool;
    public var audioListenerEnable3D: Bool;
    public var canvasCullMask: Int;
    public var canvasItemDefaultTextureFilter: Int;
    public var canvasItemDefaultTextureRepeat: Int;
    public var canvasTransform: Transform2D;
    public var debugDraw: Int;
    public var disable3D: Bool;
    public var fsrSharpness: Float;
    public var globalCanvasTransform: Transform2D;
    public var guiDisableInput: Bool;
    public var guiEmbedSubwindows: Bool;
    public var guiSnapControlsToPixels: Bool;
    public var handleInputLocally: Bool;
    public var meshLodThreshold: Float;
    public var msaa2D: Int;
    public var msaa3D: Int;
    public var ownWorld3D: Bool;
    public var physicsInterpolationMode: Int;
    public var physicsObjectPicking: Bool;
    public var physicsObjectPickingFirstOnly: Bool;
    public var physicsObjectPickingSort: Bool;
    public var positionalShadowAtlas16Bits: Bool;
    public var positionalShadowAtlasQuad0: Bool;
    public var positionalShadowAtlasQuad1: Bool;
    public var positionalShadowAtlasQuad2: Bool;
    public var positionalShadowAtlasQuad3: Bool;
    public var positionalShadowAtlasSize: Int;
    public var scaling3DMode: Int;
    public var scaling3DScale: Float;
    public var screenSpaceAA: Int;
    public var sdfOversize: Int;
    public var sdfScale: Float;
    public var snap2DTransformToPixels: Bool;
    public var textureMipmapBias: Float;
    public var transparentBg: Bool;
    public var useDebanding: Bool;
    public var useHdr2D: Bool;
    public var useOcclusionCulling: Bool;
    public var useTaa: Bool;
    public var useXr: Bool;
    public var vrsMode: Int;
    public var vrsTexture: Texture2D;
    public var vrsUpdateMode: Int;
    public var world3D: World3D;
    public var guiFocusChanged: Event;
    public var sizeChanged: Event;
    public function findWorld3D(): World3D;
    public function canvasCullMaskBit(layer: Int): Bool;
    public function getFinalTransform(): Transform2D;
    public function getMousePosition(): Vector2;
    public function getRenderInfo(type: Int, info: Int): Int;
    public function getScreenTransform(): Transform2D;
    public function getStretchTransform(): Transform2D;
    public function getVisibleRect(): Rect2;
    public function guiCancelDrag(): Void;
    public function guiGetDragData(): Variant;
    public function guiGetFocusOwner() : Control;
}