package sunaba;

enum abstract Monitor(Int) from Int to Int {
	var timeFps = 0;
	var timeProcess = 1;
	var timePhysicsProcess = 2;
	var timeNavigationProcess = 3;
	var memoryStatic = 4;
	var memoryStaticMax = 5;
	var memoryMessageBufferMax = 6;
	var objectCount = 7;
	var objectResourceCount = 8;
	var objectNodeCount = 9;
	var objectOrphanNodeCount = 10;
	var renderTotalObjectsInFrame = 11;
	var renderTotalPrimitivesInFrame = 12;
	var renderTotalDrawCallsInFrame = 13;
	var renderVideoMemUsed = 14;
	var renderTextureMemUsed = 15;
	var renderBufferMemUsed = 16;
	var physics2dActiveObjects = 17;
	var physics2dCollisionPairs = 18;
	var physics2dIslandCount = 19;
	var physics3dActiveObjects = 20;
	var physics3dCollisionPairs = 21;
	var physics3dIslandCount = 22;
	var audioOutputLatency = 23;
	var navigationActiveMaps = 24;
	var navigationRegionCount = 25;
	var navigationAgentCount = 26;
	var navigationLinkCount = 27;
	var navigationPolygonCount = 28;
	var navigationEdgeCount = 29;
	var navigationEdgeMergeCount = 30;
	var navigationEdgeConnectionCount = 31;
	var navigationEdgeFreeCount = 32;
	var navigationObstacleCount = 33;
	var pipelineCompilationsCanvas = 34;
	var pipelineCompilationsMesh = 35;
	var pipelineCompilationsSurface = 36;
	var pipelineCompilationsDraw = 37;
	var pipelineCompilationsSpecialization = 38;
	var monitorMax = 39;
}
