package sunaba;

enum abstract PropertyHint(Int) from Int to Int {
	var none = 0;
	var range = 1;
	var enum = 2;
	var enumSuggestion = 3;
	var expEasing = 4;
	var link = 5;
	var flags = 6;
	var layers2dRender = 7;
	var layers2dPhysics = 8;
	var layers2dNavigation = 9;
	var layers3dRender = 10;
	var layers3dPhysics = 11;
	var layers3dNavigation = 12;
	var file = 13;
	var dir = 14;
	var globalFile = 15;
	var globalDir = 16;
	var resourceType = 17;
	var multilineText = 18;
	var expression = 19;
	var placeholderText = 20;
	var colorNoAlpha = 21;
	var objectId = 22;
	var typeString = 23;
	var nodePathToEditedNode = 24;
	var objectTooBig = 25;
	var nodePathValidTypes = 26;
	var saveFile = 27;
	var globalSaveFile = 28;
	var intIsObjectid = 29;
	var intIsPointer = 30;
	var arrayType = 31;
	var localeId = 32;
	var localizableString = 33;
	var nodeType = 34;
	var hideQuaternionEdit = 35;
	var password = 36;
	var layersAvoidance = 37;
	var dictionaryType = 38;
	var toolButton = 39;
	var oneshot = 40;
	var max = 42;
}
