package lucidfx;

enum abstract Limit(Int) from Int to Int {
	var maxBoundUniformSets = 0;
	var maxFramebufferColorAttachments = 1;
	var maxTexturesPerUniformSet = 2;
	var maxSamplersPerUniformSet = 3;
	var maxStorageBuffersPerUniformSet = 4;
	var maxStorageImagesPerUniformSet = 5;
	var maxUniformBuffersPerUniformSet = 6;
	var maxDrawIndexedIndex = 7;
	var maxFramebufferHeight = 8;
	var maxFramebufferWidth = 9;
	var maxTextureArrayLayers = 10;
	var maxTextureSize1d = 11;
	var maxTextureSize2d = 12;
	var maxTextureSize3d = 13;
	var maxTextureSizeCube = 14;
	var maxTexturesPerShaderStage = 15;
	var maxSamplersPerShaderStage = 16;
	var maxStorageBuffersPerShaderStage = 17;
	var maxStorageImagesPerShaderStage = 18;
	var maxUniformBuffersPerShaderStage = 19;
	var maxPushConstantSize = 20;
	var maxUniformBufferSize = 21;
	var maxVertexInputAttributeOffset = 22;
	var maxVertexInputAttributes = 23;
	var maxVertexInputBindings = 24;
	var maxVertexInputBindingStride = 25;
	var minUniformBufferOffsetAlignment = 26;
	var maxComputeSharedMemorySize = 27;
	var maxComputeWorkgroupCountX = 28;
	var maxComputeWorkgroupCountY = 29;
	var maxComputeWorkgroupCountZ = 30;
	var maxComputeWorkgroupInvocations = 31;
	var maxComputeWorkgroupSizeX = 32;
	var maxComputeWorkgroupSizeY = 33;
	var maxComputeWorkgroupSizeZ = 34;
	var maxViewportDimensionsX = 35;
	var maxViewportDimensionsY = 36;
	var metalfxTemporalScalerMinScale = 46;
	var metalfxTemporalScalerMaxScale = 47;
}
